global using BasicBlazorLibrary.Components.BaseClasses;
global using BasicBlazorLibrary.Components.Basic;
global using BasicBlazorLibrary.Helpers;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.CollectionClasses;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Extensions.DependencyInjection;
global using AllMultiplayerGames.WebAssembly;
global using ff = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using bb = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using cc = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using BasicGameFrameworkLibrary.Core.CommonInterfaces;
global using BasicGameFrameworkLibrary.Blazor.Bootstrappers;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using GameLoaderBlazorLibrary;
global using BasicGameFrameworkLibrary.Blazor.Extensions;
global using BasicGameFrameworkLibrary.Blazor.Helpers;
global using MultiplayerGamesBlazorLoaderLibrary;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using ss = MultiplayerGamesBlazorLoaderLibrary.MainStartUp;